settings:
  title: 'Talos Bot Status Page'
  url: 'https://status.talos.tk' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Degraded Performance/Partial Outage'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Outage'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'No incidents recorded'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: Talos-Bot # unique identifier
    name: Talos
    description: 'Talos Bot' # default=empty
    url: 'http://185.208.169.84:8255' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: Talos-Bot-Dash
    name: Talos Bot Dashboard
    description: 'Talos Bots Dashboard'

    url: 'https://dashboard.talos.tk'
    method: GET
    expectStatus: 200

